### ISSUE TITLE
Source code for `notion-ai-alfred-workflow` command

### ISSUE THREAD

**Issue by kk17** [liCells/alfred-workflow#1]
The notion ai workflow is very useful. Any plan to opensource the source code for `notion-ai-alfred-workflow` command? I want to add more feature for it.

**Comment by liCells** [comment]
Sorry, I've been too busy recently, I'll deal with it in two or three days.

**Comment by kk17** [comment]
Just curious, are you using Golang for the notion ai API? Btw, I found a Python package for notion ai API https://github.com/Vaayne/notionai-py

**Comment by liCells** [comment]
Use this [Notion AI-go](https://github.com/jyz0309/NotionAI-go)

**Comment by liCells** [comment]
This repository is the corresponding source code.
[Notion-ai-go](https://github.com/liCells/notion-ai-go)
