### ISSUE TITLE
vm命令无效

### ISSUE THREAD

**Issue by niyuanfa** [liCells/alfred-workflow#3]
vm命令无效,cm，jm都ok

**Comment by liCells** [comment]
我重新提交了，之前修改过脚本，但是忘记同步了。
添加了登录，不用再去复制token了，修复了无法查看会议的问题。
[Tencent-Meeting-Tool](https://github.com/liCells/alfred-workflow/raw/main/Tencent-Meeting-Tool/Tencent%20Meeting%20Tool.alfredworkflow)
